# Generated by Django 4.1.3 on 2022-12-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0004_remove_driver__id_driver_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='standing',
        ),
    ]
