# Generated by Django 4.1.3 on 2022-12-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_remove_car__id_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='score',
        ),
    ]
