# Generated by Django 4.1.3 on 2022-12-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_remove_car_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='standing',
        ),
    ]
