# Generated by Django 4.1.2 on 2022-11-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Race', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='_id',
        ),
        migrations.AddField(
            model_name='race',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
