# Generated by Django 4.1.2 on 2022-11-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Race', '0002_remove_race__id_race_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Race',
        ),
    ]
